name: Daily MTI Scrape

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run fetch:mti

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "daily update" || echo "no changes"
          git push
